<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <IsWindows>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))</IsWindows>
    <IsMac>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))</IsMac>
    <IsLinux>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))</IsLinux>
  </PropertyGroup>
  
  <PropertyGroup>
    <!-- Possible values: V143, Clang_Mac, Clang_Linux, llvm, Clang, ClangCL, MSFS, Unknown-->
    <!-- Select toolset based on target GodotPlatform. Switches Cpp dialect a bit -->
    <PlatformToolset Condition="$(IsWindows)">V143</PlatformToolset>
    <PlatformToolset Condition="$(IsMac)">Clang_Mac</PlatformToolset>
    <PlatformToolset Condition="$(IsLinux)">Clang_Linux</PlatformToolset>
  </PropertyGroup>

  <!-- Build/Rebuild/Clean targets for NMake are defined in MSVC, so we need to provide them, when using MSBuild without MSVC targets -->
  <Target Name="Build">
    <Exec Command="$(NMakeBuildCommandLine)"
          WorkingDirectory="$(NMakeWorkingDirectory)"/>
  </Target>
  <Target Name="Rebuild">
    <Exec Command="$(NMakeReBuildCommandLine)"
          WorkingDirectory="$(NMakeWorkingDirectory)"/>
  </Target>
  <Target Name="Clean">
    <Exec Command="$(NMakeCleanCommandLine)"
          WorkingDirectory="$(NMakeWorkingDirectory)"/>
  </Target>

</Project>
